window.InmoSanityConfig = {
	projectId: "pv96nhm8",
	dataset: "production",
	apiVersion: "2026-04-02",
	useCdn: false,
	timeoutMs: 8000,
	liveRefreshIntervalMs: 2500,
	listenDebounceMs: 250,
	listenVisibility: "query",
	defaultDurationMs: 20000,
	panelRevealDelayMs: 1000,
	tvPerformanceMode: true,
	panelDynamicBlur: true,
	imageFormat: "auto",
	imageQuality: 68,
	imageMaxWidth: 1920,
	imageMaxHeight: 3200,
	publicBaseUrl: "",
	settingsType: "siteSettings",
	propertyType: "inmueble",
	propertyTypes: ["inmueble", "property"],
};